# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{heater}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Chandler"]
  s.date = %q{2010-04-22}
  s.email = %q{chris@flatterline.com}
  s.files = [
    "lib/heater.rb",
     "lib/heater/point.rb",
     "lib/heater/point_set.rb"
  ]
  s.homepage = %q{http://github.com/cchandler/heater}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A simple gem for interacting with heater.}
  s.test_files = [
    "spec/units/api_spec.rb",
     "spec/integrations/integrations_helper.rb",
     "spec/spec_helper.rb",
     "spec/units/units_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 1.4.2"])
    else
      s.add_dependency(%q<rest-client>, [">= 1.4.2"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 1.4.2"])
  end
end

